sudo: required
language: python
cache: pip
services:
- docker
python:
- '3.6'
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_c464028ef8d3_key -iv $encrypted_c464028ef8d3_iv
    -in deploy_rsa.enc -out ./deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_rsa
- echo -e "Host $STAGING_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_rsa

script:
- ssh -i ./deploy_rsa $STAGING_SERVER_USER@$STAGING_SERVER "cd ~/git/rufus; docker-compose down; git pull; export BOT_TOKEN=$BOT_TOKEN; docker-compose build; docker-compose up -d; printf 'export WOLFRAM_API_KEY="'$WOLFRAM_API_KEY'"\nexport BOT_TOKEN="'$BOT_TOKEN'"\nexport OSU_API_KEY="'$OSU_API_KEY'"\nexport OMDB_API_KEY="'$OMDB_API_KEY'"\nexport LASTFM_API_KEY="'$LASTFM_API_KEY'"\nexport STAGING_SERVER_USER="'$STAGING_SERVER_USER'"\nexport STAGING_SERVER="'$STAGING_SERVER'"\nexport WEBHOOK_URL="'$WEBHOOK_URL'"' > ~/autogen_travis_keys"

after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh success $WEBHOOK_URL
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh failure $WEBHOOK_URL
