sudo: required
language: python
cache: pip

services:
- docker

python:
- '3.6'

notifications:
  email: false

install:
- pip install docker
- pip install docker-compose

before_script:
- which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
- eval $(ssh-agent -s)
- ssh-keyscan -H $STAGING_SERVER >> ~/.ssh/known_hosts
- echo "$TRAVIS_SSH_PRIVATE" > ~/.ssh/TRAVIS_KEY
- chmod 600 ~/.ssh/TRAVIS_KEY

script:
- yes keyless | ssh -p22 -o StrictHostKeyChecking=no -i ~/.ssh/TRAVIS_KEY $STAGING_SERVER_USER@$STAGING_SERVER
  "wall ASD"

env:
  global:
    secure: "OwuvKBJh+3egj6Qqr166R/EU5zBAVjt+dmvpu8XKnfC10LKzKCpqJ1hqe7b0vu3sWrJYBnvEDovlq/zLaWtAqPnicO98V0fDEMU+uMaPqB/YAGVLI3igCz4Qw0zvQl/bW/BWJ0ONIKspVjYEbmTEI5Pa5sUMqG1qj7vs9Yr8it1gSiKyqmnDBnrqParEOs/xx3mtPJ5xiNi4F5pgaOlAued3ZUazI/xd3GtMB7x3+e1nAWBBA+ZQw9Qx3RifdLPHM1aJepYkB7MBVp0geB/n10yijlqg0uChihr8pNOA+pt81k/jAzkY+puFvu7Nfz1tVIdKBTF4W9IVqu+g+ZfFK5M0m02Ib7GVxb33+VQPvtabjPwBXMVi2jIOhcTMi66e6TE1u/C/RzgGwvUfAnKhZN2T09is38xxfb6ayeD3L7DeaZYnkifftDiZWAViRmBdtVjcIUHgoHTBeVaeX2GlycgZZaHa0CGQOubHuzGUSPLeiHoVdn3iV1PbRmRF7XoidKODOPaz862b1D7TTA4tsBq+NeOkYkGBbc8zlVEDm/qM7wXKMhTUblg4hcTJsItBvtyY0tFGOJ1z7btVVGzq1XwXGccQAmsbDJEWQ2AgVpVDFPces23tJfDUhXOkPbxcrFAPHXieaCk42SywMI5Pg9sAoQ6kJvqujOUcLYLhz54="
