sudo: required
language: python
cache: pip

services:
  - docker

python:
  - "3.6"

notifications:
  email: false

install:
  - pip install docker
  - pip install docker-compose

before_script:
  - cd
  - echo $TRAVIS_ID_RSA > .ssh/id_rsa
  
script:
  - ssh -p22 $STAGING_SERVER_USER@$STAGING_SERVER "wall ASD"