sudo: required
language: python
cache: pip

services:
  - docker

python:
  - "3.6"

notifications:
  email: false

install:
  - pip install docker
  - pip install docker-compose

before_script:
  - cd
  - echo "-----BEGIN RSA PRIVATE KEY-----"$TRAVIS_ID_RSA"-----END RSA PRIVATE KEY-----" > ~/.ssh/id_rsa
  - ssh-keyscan -H $STAGING_SERVER >> ~/.ssh/known_hosts
  
script:
  - ssh -p22 $STAGING_SERVER_USER@$STAGING_SERVER "wall ASD"