sudo: required
language: python
cache: pip

services:
  - docker

python:
  - "3.6"

notifications:
  email: false

install:
  - pip install docker
  - pip install docker-compose

before_script:
  - ssh-keyscan -H $STAGING_SERVER >> ~/.ssh/known_hosts
  - echo "-----BEGIN RSA PRIVATE KEY-----" > ~/.ssh/TRAVIS_ID_RSA
  - echo $TRAVIS_ID_RSA >> ~/.ssh/TRAVIS_ID_RSA
  - echo "-----END RSA PRIVATE KEY-----" >> ~/.ssh/TRAVIS_ID_RSA
  - chmod 600 ~/.ssh/TRAVIS_ID_RSA

script:
  - ssh -p22 -oStrictHostKeyChecking=no -i ~/.ssh/TRAVIS_ID_RSA $STAGING_SERVER_USER@$STAGING_SERVER "wall ASD"
