sudo: required
language: python
cache: pip
services:
- docker

python:
- '3.6'

notifications:
  email: false

install:
  - pip install docker
  - pip install docker-compose

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$TRAVIS_SSH_PRIVATE")
  - ssh-keyscan -H $STAGING_SERVER >> ~/.ssh/known_hosts
  - echo "$TRAVIS_SSH_PRIVATE" > ~/.ssh/TRAVIS_KEY
  - chmod 600 ~/.ssh/TRAVIS_KEY

script:
  - ssh -p22 -o StrictHostKeyChecking=no -i ~/.ssh/TRAVIS_KEY $STAGING_SERVER_USER@$STAGING_SERVER
    "wall ASD"

env:
  global:
    secure: gem install travis, travis encrypt TRAVIS_SSH_PRIVATE=~/.ssh/trav_rsa
