sudo: required
language: python
cache: pip

services:
  - docker

python:
  - "3.6"

notifications:
  email: false

install:
  - pip install docker
  - pip install docker-compose

before_script:
  - echo "$SSH_PUBLIC_KEY" > ~/.ssh/authorized_keys

  - ssh-keyscan -H $STAGING_SERVER >> ~/.ssh/known_hosts

  - echo "-----BEGIN OPENSSH PRIVATE KEY-----" > ~/.ssh/id_ed25519
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' >> ~/.ssh/id_ed25519
  - echo "-----END OPENSSH PRIVATE KEY-----" >> ~/.ssh/id_ed25519

  - chmod 600 ~/.ssh/id_ed25519

script:
  - ssh -p22 -oStrictHostKeyChecking=no -i ~/.ssh/id_ed25519 $STAGING_SERVER_USER@$STAGING_SERVER "wall ASD"
