sudo: required
language: python
cache: pip

services:
- docker

python:
- '3.6'

notifications:
  email: false

install:
- pip install docker
- pip install docker-compose

before_script:
- which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
- eval $(ssh-agent -s)
- ssh-keyscan -H $STAGING_SERVER >> ~/.ssh/known_hosts
- echo "$TRAVIS_SSH_PRIVATE" > ~/.ssh/TRAVIS_KEY
- chmod 600 ~/.ssh/TRAVIS_KEY

script:
- ssh -p22 -o StrictHostKeyChecking=no -i ~/.ssh/TRAVIS_KEY $STAGING_SERVER_USER@$STAGING_SERVER
  "wall ASD"

env:
  global:
    secure: "JgEgCXKRm9IvZQFrf6WBsHvsDWRFDeAwqY2fY+gbaK4Pv2STjkOUPWXtK47FHW8ie8ASKb2pQh5QqWJSsP1OobaGOt0feJ2Hw9a71uW5fWUNbsBUCJtlXPnNvMUa3hZfoxbLMUXq398BjY+HHF/DF/71ba6RuYpPGkM2PT6pEuryvckerNVT3VLBH82YvOkpLBaOjbdxcw4YkCBw7E1tRd80i6Y9YP32nuq0szLq2qqw8Y0MYOcN4IY0Bm9R1A+Zt3SLqlSfDaIh1bqXyfZY4AxcTt9qjFP/rsOrwc2naL000iXbOJpyIEN0O+/2MvYQy6MLVHAIw33cj0V7lBf5mhJSWl9ly3A7Itn80JZB0Q+e3uSpwOofm20Uzq1NAPn41V0ozVy0KyjEgvKAsL7ccXt7OuA7dMIbLOoxd6PudfzyXtSHL34f3ycewKs4SDiAJygd2JXDF5510U+DaxBQKhtNPIN4fxZRxLI0acIeldzCn2p1pBbErNohjV+knJTqLuToKoWBSesYdnyq12FxtEAHXqU6iE0kMksTPhdtvCH4ohIpXTcVPM4FWGpC+lbJ6xbNw7bE3LVDrNDqC6r85C0z240P4D+AkGdIw6awN3nYcH6FSieK8hIxpx0S8mHEZ26fwRSl9UPlSBMYSdcLXzcpfmOBfVrAkuonIPwNgmQ="
