version: "3"

services:
  rufus:
    container_name: rufus
    hostname: rufus
    restart: unless-stopped
    image: rufus
    build:
      context: .
    environment:
        - BOT_TOKEN=$BOT_TOKEN
    ports:
      - 8080:8080
