version: "3"

services:
  rufus:
    container_name: rufus
    hostname: rufus
    restart: unless-stopped
    image: rufus
    build:
      context: .
    environment:
        - BOT_TOKEN=$BOT_TOKEN
        - TRAVIS_ID_RSA=$SSH_PRIVATE_KEY
    ports:
      - 8080:8080
